<template>
  <div v-scroll="onScroll">
    <PageHeader v-bind:value="header" v-bind:scrollY="scrollY"></PageHeader>
    <PageBody v-bind:app="sections"></PageBody>
    <PageFooter v-bind:value="footer"></PageFooter>
    <ScrollTopButton v-bind:scrollY="scrollY"></ScrollTopButton>
    <PreloaderOverlay></PreloaderOverlay>
  </div>
</template>

<script>
import PageHeader from './components/PageHeader.vue';
import PageBody from './components/PageBody.vue';
import PageFooter from './components/PageFooter.vue';
import ScrollTopButton from './components/ScrollTopButton.vue';
import PreloaderOverlay from './components/PreloaderOverlay.vue';

import AboutJpg from './assets/img/about.jpg';

import HeaderJson from './assets/data/header.json'
import HeroJson from './assets/data/hero.json';
import WhatWeDoJson from './assets/data/whatwedo.json';
import AboutUsJson from './assets/data/aboutus.json';
import SkillsJson from './assets/data/skills.json';
import StatsJson from './assets/data/stats.json';
import ServicesJson from './assets/data/services.json';
import PortfolioJson from './assets/data/portfolio.json';
import TestimonialsJson from './assets/data/testimonials.json';
import TeamJson from './assets/data/team.json';
import ContactJson from './assets/data/contact.json';
import FooterJson from './assets/data/footer.json';

export default {
  name: 'App',
  components: {
    PageHeader,
    PageBody,
    PageFooter,
    ScrollTopButton,
    PreloaderOverlay
  },
  data() {
    // Resolves image path generated by webpack during compilation
    AboutUsJson.image = AboutJpg

    return {
      // Replaces toggleScrollTop() in ScrollTopButton.vue using bound data.
      scrollY: window.scrollY,
      header: HeaderJson,
      sections: {
        hero: HeroJson,
        whatWeDo: WhatWeDoJson,
        aboutUs: AboutUsJson,
        skills: SkillsJson,
        stats: StatsJson,
        services: ServicesJson,
        portfolio: PortfolioJson,
        testimonials: TestimonialsJson,
        team: TeamJson,
        contact: ContactJson,
      },
      footer: FooterJson
    }
  },
  mounted() {
    /**
     * Template Name: Lumia
     * Template URL: https://bootstrapmade.com/lumia-bootstrap-business-template/
     * Updated: Aug 07 2024 with Bootstrap v5.3.3
     * Author: BootstrapMade.com
     * License: https://bootstrapmade.com/license/
     */

    /**
     * Apply .scrolled class to the body as the page is scrolled down
     */
    this.onScroll();

    /**
     * Correct scrolling position upon page load for URLs containing hash links.
     */
    if (window.location.hash) {
      if (document.querySelector(window.location.hash)) {
        setTimeout(() => {
          let section = document.querySelector(window.location.hash);
          let scrollMarginTop = getComputedStyle(section).scrollMarginTop;
          window.scrollTo({
            top: section.offsetTop - parseInt(scrollMarginTop),
            behavior: 'smooth'
          });
        }, 100);
      }
    }
  },
  methods: {
    onScroll() {
      // Update vertical position.
      // Replaces toggleScrollTop() in ScrollTopButton.vue using bound data.
      this.scrollY = window.scrollY;

      this.toggleScrolled()
    },
    toggleScrolled() {
      const selectBody = document.querySelector('body');
      const selectHeader = document.querySelector('#header');
      if (!selectHeader.classList.contains('scroll-up-sticky') && !selectHeader.classList.contains('sticky-top') && !selectHeader.classList.contains('fixed-top')) return;
      this.scrollY > 100 ? selectBody.classList.add('scrolled') : selectBody.classList.remove('scrolled');
    },
  },
}
</script>
